version: "3.8"
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "1k"
    max-file: "3"

services:
  web:
    build:
      context: "./web"
      dockerfile: "Dockerfile"
    volumes:
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    logging: *default-logging
  backend:
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    logging: *default-logging

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"

  redis:
    image: redis:alpine
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    restart: always
    logging: *default-logging